server:
  port: 8090
spring:
  profiles:
    active: prod
jwt:
  token:
    secret: jwtTFCsecret
    expire: 100000000
---
#----DEV----
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2-data/testdb;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    url: jdbc:h2:file:./h2-data/testdb
    user: sa
    password:
    locations: classpath:db/migration, classpath:db/test-data


---
#----UAT----
spring:
  profiles: uat
  datasource:
    url: jdbc:postgresql://ec2-54-246-85-151.eu-west-1.compute.amazonaws.com:5432/d709fb3dvsh8de
    username: ukmokwxdmoebne
    password: 14c9bc1965da668f5cc0adffb85675272193631912fb4954292aebf78a928633
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: off
